[package]
name = "hv-cpu"
description = "CPU capability probing for the Hypster hypervisor"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []
std = ["hv-types/std"]

[dependencies]
hv-types = { workspace = true }
hv-x86 = { workspace = true }

[lints]
workspace = true
