//! Embeds resolved Gate D plans from `configs/qemu.yaml` at build time.

#![allow(clippy::expect_used)]

use std::path::PathBuf;

use hv_core::platform_ir::StaticPlatformIR;
use hv_partition::gate_d_plans_from_resolved;
use hv_runtime::GateDPlans;

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    println!("cargo:rerun-if-changed=configs/qemu.yaml");
    println!("cargo:rerun-if-changed=hypster.ld");
    println!("cargo:rustc-link-arg=-T{}/hypster.ld", manifest_dir.display());
    let workspace = manifest_dir.parent().expect("workspace root");
    let config_path = workspace.join("configs/qemu.yaml");

    let raw =
        hv_config_model::yaml::read_yaml_file(config_path.to_str().expect("config path utf8"))
            .expect("read qemu.yaml");
    let compiled = hv_config_model::pipeline::compile_config(raw).expect("compile config");
    let observed = hv_core::fixture::qemu_validation_observed().expect("fixture");
    let platform =
        hv_core::resolve_platform(&compiled.intent, &observed).expect("resolve platform");
    let plans = gate_d_plans_from_resolved(&platform);

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let path = out_dir.join("gate_d_plans.rs");
    if std::fs::write(path, render_gate_d_plans(&platform, &plans)).is_err() {
        std::process::exit(1);
    }
}

fn render_gate_d_plans(platform: &StaticPlatformIR, plans: &GateDPlans) -> String {
    let mut out = String::from("// @generated by hypervisor/build.rs\n\n");
    out.push_str("use hv_config_model::hash::ConfigHash;\n");
    out.push_str(
        "use hv_ept::{EptMapping, EptMemoryType, EptPartitionPlan, EptPermissions, EptPlan};\n",
    );
    out.push_str("use hv_runtime::{GateCPlans, GateDPlans, IpcChannelPlan};\n");
    out.push_str("use hv_types::{GuestPhysAddr, HostPhysAddr, IommuDomainId, VmId};\n");
    out.push_str("use hv_vtd::{VtdDomainPlan, VtdPlan};\n\n");
    out.push_str("pub fn embedded_gate_d_plans() -> GateDPlans {\n");
    out.push_str(&format!(
        "    let config_hash = ConfigHash([{}]);\n",
        platform
            .config_hash
            .bytes()
            .iter()
            .map(|byte| byte.to_string())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    out.push_str("    GateDPlans {\n");
    out.push_str("        gate_c: GateCPlans {\n");
    out.push_str(&render_ept_plan(&plans.gate_c.ept));
    out.push_str(&render_vtd_plan(&plans.gate_c.vtd));
    out.push_str(&format!(
        "            ept_table_base: HostPhysAddr::new({}),\n",
        plans.gate_c.ept_table_base.raw()
    ));
    out.push_str(&format!(
        "            vtd_table_base: HostPhysAddr::new({}),\n",
        plans.gate_c.vtd_table_base.raw()
    ));
    out.push_str(&format!(
        "            vmxon_region_base: HostPhysAddr::new({}),\n",
        plans.gate_c.vmxon_region_base.raw()
    ));
    out.push_str("        },\n");
    out.push_str("        ipc_channels: alloc::vec![");
    for channel in &plans.ipc_channels {
        out.push_str("\n            IpcChannelPlan {");
        out.push_str(&format!(
            "\n                name: alloc::string::String::from({:?}),",
            channel.name
        ));
        out.push_str(&format!("\n                slot_count: {},", channel.slot_count));
        out.push_str(&format!("\n                slot_size: {},", channel.slot_size));
        out.push_str(&format!(
            "\n                host_base: HostPhysAddr::new({}),",
            channel.host_base.raw()
        ));
        out.push_str(&format!("\n                shared_bytes: {},", channel.shared_bytes));
        out.push_str("\n            },");
    }
    out.push_str("\n        ],\n");
    out.push_str("        config_hash,\n");
    out.push_str("        require_config_hash: true,\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn render_ept_plan(plan: &hv_ept::EptPlan) -> String {
    let mut out = String::from("            ept: EptPlan { partitions: alloc::vec![");
    for partition in &plan.partitions {
        out.push_str("\n                EptPartitionPlan {");
        out.push_str(&format!(
            "\n                    vm_id: VmId::new({}),",
            partition.vm_id.raw()
        ));
        out.push_str("\n                    mappings: alloc::vec![");
        for mapping in &partition.mappings {
            out.push_str("\n                        EptMapping {");
            out.push_str(&format!(
                "\n                            guest_phys: GuestPhysAddr::new({}),",
                mapping.guest_phys.raw()
            ));
            out.push_str(&format!(
                "\n                            host_phys: HostPhysAddr::new({}),",
                mapping.host_phys.raw()
            ));
            out.push_str(&format!("\n                            size: {},", mapping.size));
            out.push_str(&format!(
                "\n                            permissions: {},",
                render_permissions(&mapping.permissions)
            ));
            out.push_str(&format!(
                "\n                            memory_type: {},",
                render_memory_type(mapping.memory_type)
            ));
            out.push_str("\n                        },");
        }
        out.push_str("\n                    ],");
        out.push_str("\n                },");
    }
    out.push_str("\n            ] },\n");
    out
}

fn render_permissions(permissions: &hv_ept::EptPermissions) -> &'static str {
    if permissions.read && permissions.write && permissions.execute {
        "EptPermissions::GUEST_RAM"
    } else if permissions.read && permissions.write && !permissions.execute {
        "EptPermissions::MMIO"
    } else {
        "EptPermissions { read: false, write: false, execute: false }"
    }
}

fn render_memory_type(memory_type: hv_ept::EptMemoryType) -> &'static str {
    match memory_type {
        hv_ept::EptMemoryType::WriteBack => "EptMemoryType::WriteBack",
        hv_ept::EptMemoryType::Uncacheable => "EptMemoryType::Uncacheable",
    }
}

fn render_vtd_plan(plan: &hv_vtd::VtdPlan) -> String {
    let mut out = String::from("            vtd: VtdPlan { domains: alloc::vec![");
    for domain in &plan.domains {
        out.push_str("\n                VtdDomainPlan {");
        out.push_str(&format!(
            "\n                    domain_id: IommuDomainId::new({}),",
            domain.domain_id.raw()
        ));
        out.push_str(&format!("\n                    vm_id: VmId::new({}),", domain.vm_id.raw()));
        out.push_str("\n                    devices: alloc::vec![");
        for device in &domain.devices {
            out.push_str(&format!("alloc::string::String::from({device:?}),"));
        }
        out.push_str("],");
        out.push_str("\n                    mappings: alloc::vec![],");
        out.push_str("\n                },");
    }
    out.push_str("\n            ] },\n");
    out
}
