[package]
name = "hv-ept"
description = "EPT planning for Hypster partitions"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []
std = ["hv-types/std"]

[dependencies]
hv-types = { workspace = true }
hv-config-model = { workspace = true, features = ["std"] }
hv-memory = { path = "../hv-memory" }

[lints]
workspace = true
